eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
 microservice:
   document-service:
      endpoints:
         endpoint:
            uri: http://DOCUMENT-SERVICE/
            
 #  order-service:
 #     endpoints:
 #        endpoint:
 #           uri: http://ORDER-SERVICE/order/bookOrder   
   
