eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
 microservice:
   payment-service:
      endpoints:
         endpoint:
            uri: http://PAYMENT-SERVICE/paymentservice/doPayment
            
   order-service:
      endpoints:
         endpoint:
            uri: http://ORDER-SERVICE/order/bookOrder   
   
